name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify directory structure
        run: |
          ls -la  # List all files to ensure EventManagementSystem folder is where it should be

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          ls -la  # List files again after checkout to verify correct directory
          composer install

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit
